# Generated by Django 6.0.6 on 2026-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(default="Guest", max_length=100),
        ),
    ]
