# Generated by Django 6.0.6 on 2026-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
