# Generated by Django 6.0.6 on 2026-07-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_customer_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_small", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_medium", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_large", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="allow_toppings",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrderItemTopping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toppings",
                        to="orders.orderitem",
                    ),
                ),
            ],
        ),
    ]
